displayName = "EN"
isoCode = "en"
languageCode = "en"
languageName = "English"
rtl = false
weight = 1

description = "My awesome website"
title = "Genevieve Curry"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "January 2, 2006"

[params]
# mainSections = ["section1", "section2"]

[author]
bio = "Full-stack software engineer with a knack for problem soliving. Whether it's developing back-end systems or crafting front-end interfaces, I love to bring ideas to life through code."
headline = "100% human"
image = "img/author.jpg"
links = [
  {linkedin = "https://www.linkedin.com/in/genevieve-curry/"},
  {github = "https://github.com/genevievecurry"},
]
name = "Genevieve Curry"
