languageCode = "fr"
languageName = "French"
displayName = "FR"
isoCode = "fr"
weight = 1
rtl = false

title = "Genevieve Curry"
description = "Mon super site web"
# copyright = "Copy, right? :thinking_face:"

dateFormat = "2 janvier 2006"

[params]
# mainSections = ["section1", "section2"]

[author]
name = "Genevieve Curry"
image = "img/author.jpg"

headline = "Je suis juste humaine"
bio = "Un petit peu à propos de vous"
