# -- Menu Principal --
# Le menu principal est affiché dans l'en-tête en haut de la page.
# Les paramètres acceptables sont : name, pageRef, page, url, title, weight.
# La configuration la plus simple du menu consiste à fournir :
# name = Le nom à afficher pour ce lien de menu
# pageRef = L'identifiant de la page ou de la section vers laquelle faire un lien
# Par défaut, le menu est trié par ordre alphabétique. Cela peut être
# contourné en fournissant une valeur de poids. Le menu sera ensuite
# trié par poids, du plus bas au plus haut.

[[main]]
name = "À propos de moi"
pageRef = "about"
weight = 10

[[main]]
name = "Travail"
pageRef = "work"
weight = 20

[[main]]
name = "Jouer"
pageRef = "hobby"
weight = 30


# -- Menu de bas de page --
# Le menu de bas de page est affiché en bas de la page, juste avant
# l'avis de droits d'auteur. Configurez comme le menu principal ci-dessus.
